### PR TITLE
Removed broken link.

### PR DESCRIPTION
**Pull request by milanchheda**
Hi there! Thanks so much for submitting a pull request!

Let's just make sure together that all of these boxes are checked before we
merge this change:

- [x] The code in these changes works correctly.
- [x] Code has tests as appropriate.
- [x] Code has been reviewed by @JacobEvelyn.
- [x] All tests pass on TravisCI.
- [x] Rubocop reports no issues on TravisCI.
- [x] The `README.md` file is updated as appropriate.

Don't worry—this list will get checked off in no time!

Removed broken link.

### CODE REVIEW

**Comment by JacobEvelyn** [comment]
Hi @milanchheda! Thanks so much for making this pull request! I think `badge.fury.io` had some downtime earlier but it seems to be fixed now, and the link does work. Or is there something I'm missing?

**Comment by milanchheda** [comment]
@JacobEvelyn - Yes, it was broken yesterday. Seems it's fixed now.

**Comment by milanchheda** [comment]
@JacobEvelyn - When I raised a pull request, I saw that description was auto-populated with below message: 

> Hi there! Thanks so much for submitting a pull request!
> 
> Let's just make sure together that all of these boxes are checked before we
> merge this change:
> 
>  The code in these changes works correctly.
>  Code has tests as appropriate.
>  Code has been reviewed by @JacobEvelyn.
>  All tests pass on TravisCI.
>  Rubocop reports no issues on TravisCI.
>  The README.md file is updated as appropriate.
> Don't worry—this list will get checked off in no time!
> 
> Removed broken link
> 

How is this done?

I am sorry, asking here but wasn't sure where else I can ask/learn this from you.

**Comment by JacobEvelyn** [comment]
Hey @milanchheda no need to apologize, and great question! This is done with the [`PULL_REQUEST_TEMPLATE.md`](https://github.com/JacobEvelyn/friends/blob/master/PULL_REQUEST_TEMPLATE.md) file in the base of this repository. This is a relatively new feature of GitHub; here's some more info about this and some related functionality: https://github.com/blog/2111-issue-and-pull-request-templates

Hope that helps!

**Pull request closed without merging**
