### PR TITLE
added new command stats

### PR DESCRIPTION
**Pull request by sivakb**
Hi @JacobEvelyn 

Just added stats command to list Total no of friends and activities.

https://github.com/JacobEvelyn/friends/issues/36

### CODE REVIEW

**Comment by JacobEvelyn** [comment]
Thanks so much for contributing! I've added a few small comments to your pull request.

In addition, I'd love if you could write tests for this as well; see the `introvert_spec.rb` file for more details, and I'm happy to help guide you through that as well.

Lastly, I'd love to see if this command could also return the elapsed time period, as shown in #36. I'm more than happy to help you write that code as well!

Lastly, since you're the first external contributor to this project (wooo!), let me know if there are things I can do (add to the `README`, write a `CONTRIBUTING.md` file, add labels for Issues that others can take, etc.) to make this process smoother!

**Comment by sivakb** [comment]
@JacobEvelyn  added test cases and modified the code as per your comments. for return the elapsed time period can tell me how you expect output ?

e.g:

we have two activity

2015-11-01: Grace Hopper and I went to Marie's Diner. George had to cancel at the last minute.
2015-01-04: Got lunch with Grace Hopper and George Washington Carver.

Subtract each activity date form today and sum ?

**Comment by JacobEvelyn** [comment]
Thanks for making those changes!

Subtracting each activity date from the current day and summing would yield quite a large number, but I don't see what that number would really represent. What I was looking for is the total elapsed days of activities recorded, so something like this:

```ruby
def elapsed_days
  return 0 if @activities.size < 2

  (@activities.last.date - @activities.first.date).to_i
end
```

And use it like:
```ruby
days = @introvert.elapsed_days
"Total time elapsed: #{days} day#{'s' if days != 1}"
```

Does that make sense? Do you see a better stat to display instead?

**Comment by sivakb** [comment]
@JacobEvelyn  Added elapsed days

**Comment by JacobEvelyn** [comment]
Hey! Thanks so much for working on this, and sorry it still hasn't been merged. I have some more feedback on the PR that I added via comments.

I know it can be frustrating to have a feature get slowed down by a lot of back-and-forth in code review so if it's easier I can make a new branch, cherry-pick your commits onto it and then add my own commit to tidy up the code (it won't take me long and really is no trouble). I thought I'd give you an opportunity to make the changes first though before I barged in on your work. :smiley: 

Let me know what you think!

**Comment by sivakb** [comment]
@JacobEvelyn  Thank you so much   for your reviews and detailed comments . I have modified the code as per your comments.

**Comment by JacobEvelyn** [comment]
One last comment: those `stub_friends` and `stub_activities` methods should only affect things within their blocks, like `MiniTest`'s native stubs. To ensure this, I just pushed a new commit that enforces this behavior in how `stub_friends` and `stub_activities` are defined. (If you rebase on top of that new commit, you'll see that your tests fail.)

To fix this, please put your test assertions within the blocks (any time you have an empty block, as you do currently, that should be a red flag that something's not right).

**Comment by sivakb** [comment]
@JacobEvelyn Thanks you so much for you valuable comments. As you said early Please  cherry-pick the commit and to new branch.

This my first pull request to a open source. I learn Many things from your Comments. Thank you So much for that.

**Comment by JacobEvelyn** [comment]
No problem, and glad you've learned! If you're curious, here's the last commit I did: https://github.com/JacobEvelyn/friends/commit/760517eae551cc746f9415521a0865b66606764e

Thanks for doing all of the heavy lifting on this PR, and congrats on your first piece of open-source work! You're a [contributor](https://github.com/JacobEvelyn/friends/graphs/contributors) now! :smile_cat:

**Comment by sivakb** [comment]
@JacobEvelyn  Thank you :) , Checked your last Commit :+1:

**Pull request closed without merging**
