### PR TITLE
Fix failing test and add rubocop

### PR DESCRIPTION
**Pull request by shen-sat**
Hi @JacobEvelyn it's me, the first-time open-source contributor :)

This is my first ever pull request of this nature, so I hope you don't mind me going through my changes in detail. Happy to discuss further if you want to 👍 

- First commit: Once I cloned the repo, I tried to run tests with `rake tests` but one test kept failing with the message: `NameError: uninitialized constant Friends::POST_INSTALL_MESSAGE` so I required the relevant module in the relevant test and then the failing test passed
- Second commit: I then tried to run `bundle exec rubocop .` but I got the error: `bundler: command not found: rubocop`. I looked in the gemspec and couldn't see rubocop anywhere, so I added it
- Third commit: I tried to run `bundle exec rubocop .` again and I got a different error: `Error: RuboCop found unsupported Ruby version 2.2 in `TargetRubyVersion` parameter (in .rubocop.yml). 2.2-compatible analysis was dropped after version 0.69.
Supported versions: 2.3, 2.4, 2.5, 2.6, 2.7` - so I changed the targeted ruby version in `.rubocop.yml` from 2.2 to 2.3
- Fourth commit: I then ran `bundle exec rubocop .` and it it picked up errors, so to fix them, I ran `bundle exec rubocop . -a`

I hope that makes sense. Completely understand I may be making lots of mistakes here as this is my first time working with a project I'm unfamilar with. Let me know what you think :)

PS I'll start on the issue you assigned my once we've discussed this request

---

Hi there! Thanks so much for submitting a pull request!

Let's just make sure together that all of these boxes are checked before we
merge this change:

- [ ] The code in these changes works correctly.
- [ ] Code has tests as appropriate.
- [ ] Code has been reviewed by @JacobEvelyn.
- [ ] All tests pass on Travis CI.
- [ ] Code coverage remains high.
- [ ] Rubocop reports no issues on Travis CI.
- [ ] The `README.md` file is updated as appropriate.

Don't worry—this list will get checked off in no time!

### CODE REVIEW

**Comment by JacobEvelyn** [comment]
Hey @shen-sat ! Thank you *so much* for such a thoughtful and thorough PR! For an open-source newbie, this is an impressive first contribution and I really appreciate the time you took to explain everything so clearly.

It looks like a lot of your pain was caused by my having outdated instructions in [CONTRIBUTING.md](https://github.com/JacobEvelyn/friends/blob/master/.github/CONTRIBUTING.md). So sorry about that!

For example, you're right that `rake test` leads to that one test failing. However, `bundle exec rake test`, which is [what our Travis CI test setup runs](https://github.com/JacobEvelyn/friends/blob/master/.travis.yml#L9), has all tests passing. I think my vote there would be to just change the `CONTRIBUTING.md` file, unless you know of a reason why changing the code is better (I don't know a ton about `require` behavior so there very well could be a reason!).

Similarly, I removed `rubocop` from being a development dependency in the `friends.gemspec` because people kept running into issues using it locally, especially since the latest version doesn't support older versions of Ruby that `friends` [does](https://github.com/JacobEvelyn/friends/blob/master/friends.gemspec#L28). (I know that our `TargetRubyVersion: 2.2` is newer than the `2.1` version we support in the gemspec; if I remember correctly that's because `TargetRubyVersion: 2.1` hasn't been supported in a long time and we're not actually using any 2.2+ features, as tested by the 2.1 tests passing in Travis.) So the last time I touched this I thought the easiest thing was to just have Travis CI [install the latest version that works](https://github.com/JacobEvelyn/friends/blob/master/.travis.yml#L15) and run that once. It could get _slightly_ annoying to add `rubocop` to the gemspec and pin it at `v0.67` because Dependabot will then keep making PRs to try to update it, but that's not a big deal. So I'd vote for either:

1. Update `CONTRIBUTING.md` to tell contributors to just look at the RuboCop output in Travis, or
2. Add it to the gemspec, but pin it at version `0.67` so that it doesn't hate the Ruby 2.1-compatible code.

That's ^ a lot—let me know if any of that could use more explanation!

One more thing: in the Travis tests for your PR, I noticed that the Ruby 2.6 tests [seem to be failing with `simplecov` errors](https://travis-ci.com/JacobEvelyn/friends/jobs/236977550). I'm happy to look into that, but also happy to let you investigate if you'd like!

**Comment by shen-sat** [comment]
Hey @JacobEvelyn thank you so much for the comments! And no worries about the `CONTRIBUTING.md`, I'll be happy to update it 👍 

I'm intrigued as to why that one test fails when running `rake test` but not with `bundle exec rake test`, so I 've been looking a bit into that this evening, just for my own learning. But I agree with you, a simple edit to the `CONTRIBUTING.md` makes sense.

With regards to rubocop, that's a tricky one! I've not used Travis CI before (I've use other CI tools though) - I'll look into it a bit more when I have time on the weekend, and make a separate pull request if that's ok? I think again you're right, an edit to the `CONTRIBUTING.md` will be the easier fix! I'll look into the `simplecov` issue too - leave it with me :)

So happy to get the ball rolling with this 🙌

**Comment by shen-sat** [comment]
Hey @JacobEvelyn, I've had a look into rubocop and dependabot - if we pin rubocop to version `0.67` and tell dependabot that we want to ignore it after its initial pull request attempt (which I've done [here using a test project](https://github.com/pulls?q=is%3Apr+review-requested%3Ashen-sat+archived%3Afalse+is%3Aclosed)) then we won't receive anymore pull requests. We could also add [an ignore command in a config file for dependabot](https://dependabot.com/docs/config-file/#ignored_updates) to make sure it doesn't even send the initial pull request (which I'm happy to create 😄).  

I'm leaning towards putting rubocop in as a project dependency rather than checking in Travis CI for rubocop errors because I (and hopefully future devs!) can increase our development speed if we can check rubocop locally rather than in Travis. What do you think?

**Comment by JacobEvelyn** [comment]
Thanks for digging, @shen-sat ! I'm happy to add it as a dev dependency and put instructions in `CONTRIBUTING.md`, but I definitely _also_ want to keep it in Travis. (I moved RuboCop from a dev dependency and `CONTRIBUTING.md` step to Travis a year or so ago when I found that it was too easy for folks to not run RuboCop and make PRs that didn't actually follow the RuboCop style.)

How does that sound?

**Comment by shen-sat** [comment]
No problemo @JacobEvelyn - it was fun learning about dependabot :) Completely understand and agree with your reasons for leaving rubocop in Travis 👍🏾 I'll make a pull request today with the rubocop dependency and a dependabot config file to ignore it. If you still end up getting pull requests to update rubocop from dependabot, please let me know and I'll look into into it 💪🏾

**Comment by JacobEvelyn** [comment]
@shen-sat does it make sense to close this? I want to make sure I'm not missing something given all of the overlapping conversations we're having 😬

**Comment by JacobEvelyn** [comment]
@shen-sat I think this is no longer needed. Please re-open if I missed something!

**Pull request closed without merging**
